#include ~/.cache/wal/colors-kitty.conf

font_family      JetBrains Mono
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic
font_size 	    11.0
background_opacity    0.7
bold_font       auto
italic_font      auto
bold_italic_font auto
hide_window_decorations yes 
confirm_os_window_close 0
enable_audio_bell no


cursor                  #928374
cursor_text_color       background

url_color               #83a598

visual_bell_color       #8ec07c
bell_border_color       #8ec07c

active_border_color     #d3869b
inactive_border_color   #665c54

foreground              #ebdbb2
background              #282828
selection_foreground    #928374
selection_background    #ebdbb2

active_tab_foreground   #fbf1c7
active_tab_background   #665c54
inactive_tab_foreground #a89984
inactive_tab_background #3c3836

# Black
color0 #665c54
color8 #7c6f64

# Red
color1 #f2594b
color9 #f2594b

# Green
color2  #b0b846
color10 #b0b846

# Yellow
color3  #e9b143
color11 #e9b143

# Blue
color4  #80aa9e
color12 #80aa9e

# Magenta
color5  #d3869b
color13 #d3869b

# Cyan
color6  #8bba7f
color14 #8bba7f

# White
color7  #e2cca9
color15 #e2cca9