#config for kitty terminal, with colors and fonts and all

font_family      GoogleSansCode
bold_font        GoogleSansCode
italic_font      GoogleSansCode
bold_italic_font GoogleSansCode
font_size 	    11.0
background_opacity    1
bold_font       auto
italic_font      auto
bold_italic_font auto
hide_window_decorations yes 
confirm_os_window_close 0
enable_audio_bell no

cursor                  #f19618
cursor_text_color       background

url_color               #36a3d9

visual_bell_color       #95e5cb
bell_border_color       #95e5cb

active_border_color     #f19618
inactive_border_color   #1f2730

foreground              #f5f0dc
background              #05080b
selection_foreground    #05080b
selection_background    #3d5568

active_tab_foreground   #ffffff
active_tab_background   #1f2a33
inactive_tab_foreground #b8c0c8
inactive_tab_background #05080b

# black
color0                  #000000
color8                  #4a5560

# red
color1                  #ff3333
color9                  #ff6565

#: green
color2                  #b8cc52
color10                 #e9fe83

# yellow
color3                  #e6c446
color11                 #fff778

# blue
color4                  #36a3d9
color12                 #68d4ff

# purple
color5                  #f07078
color13                 #ffa3aa

# aqua
color6                  #95e5cb
color14                 #c7fffc

# white
color7                  #ffffff
color15                 #ffffff
