$terminal = kitty -c ~/.config/dotfiles/kitty/kitty.conf
$browser = librewolf  
$fileManager = nautilus
$menu = rofi -config ~/.config/dotfiles/rofi/config.rasi -show drun
$discord = /usr/bin/distrobox-enter  -n Ubuntu -- /bin/sh -l -c  /usr/share/discord/Discord
$whatsapp = zapzap
$telegram = telegram-desktop
$music = librewolf --new-window https://open.spotify.com/
