$terminal = kitty -c ~/.config/dotfiles/kitty/kitty.conf
$editor = $terminal nvim
$browser = librewolf  
$fileManager = nautilus
$menu = rofi -config ~/.config/dotfiles/rofi/config.rasi -show drun
$discord = webcord
$whatsapp = zapzap
$telegram = flatpak run org.telegram.desktop
$music = librewolf --new-window https://open.spotify.com/
$localmusic = g4music
$youtube = librewolf --new-window https://www.youtube.com/feed/subscriptions
$chatgpt = librewolf --new-window https://chat.openai.com/
$gemini = librewolf --new-window https://gemini.google.com/app
