#Default Keys
$mainMod = SUPER

# Keybinds only activated while testing
bind = $mainMod SHIFT, A, exec, killall swaync && swaync -s ~/.config/dotfiles/swaync/style.css -c ~/.config/dotfiles/swaync/config.json
bind = $mainMod SHIFT, W, exec, killall waybar && waybar -c ~/.config/dotfiles/waybar/config -s ~/.config/dotfiles/waybar/style.css

#Fullscreen
bind = $mainMod, F, fullscreen,

#Screenshots (Super+Fn+Print)
bind = $mainMod, code:107, exec, hyprshot -o Pictures/Screenshots -m region
bind = $mainMod SHIFT, code:107, exec, hyprshot -o Pictures/Screenshots -m output

#Programs
bind = $mainMod, Q, exec, $terminal
bind = $mainMod SHIFT, Q, exec, gnome-terminal
bind = $mainMod, W, exec, $fileManager
bind = $mainMod, Z, exec, $browser
bind = $mainMod, A, exec, $music
bind = $mainMod SHIFT, A, exec, $localmusic
bind = $mainMod, S, exec, killall scrcpy || scrcpy --no-video
bind = $mainMod SHIFT, S, exec, killall scrcpy

#Settings
bind = $mainMod, X, exec, sleep 0.1 && swaync-client -t -sw
bind = $mainMod, C, killactive, 
bind = $mainMod, L, exec, wlogout -l /home/shub/.config/dotfiles/wlogout/layout --css /home/shub/.config/dotfiles/wlogout/style.css
bind = $mainMod, N, exec, killall swaybg && swaybg -i Pictures/wallpapers/"$(ls Pictures/wallpapers | shuf -n 1)" #New wallpapers
bind = $mainMod, V, togglefloating, 
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, R, togglesplit,
bind =, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+
bind =, XF86AudioLowerVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-
bind =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle 

#Cycle windows
bind = ALT, TAB, cyclenext

#Toggle Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

#Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

#Special workspaces (scratchpad)
bind = $mainMod, code:49, togglespecialworkspace, overveiw
bind = $mainMod SHIFT, code:49, movetoworkspace, special:overveiw

bind = $mainMod, code:67, togglespecialworkspace, videos
bind = $mainMod SHIFT, code:67, movetoworkspace, special:videos

#Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

#Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

#Move and resize windows
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d 
bind = $mainMod , right, resizeactive, 40 0
bind = $mainMod , left, resizeactive, -20 0
bind = $mainMod , up, resizeactive, 0 -20
bind = $mainMod , down, resizeactive, 0 40

