exec-once = copyq --start-server
exec-once = swaync -s ~/.config/dotfiles/swaync/style.css -c ~/.config/dotfiles/swaync/config.json
exec-once = swaybg -i Pictures/wallpapers/"$(ls Pictures/wallpapers | shuf -n 1)"
exec-once = waybar -c ~/.config/dotfiles/waybar/config -s ~/.config/dotfiles/waybar/style.css
exec-once = $terminal
exec-once = steam
exec-once = kdeconnect-cli --ping-msg "Gro-Goroth has awakened." -d 0d74fbb0_793a_4297_a291_2fc202c70e94
exec-once = [workspace 3 silent] $discord
exec-once = [workspace 4 silent] $whatsapp
exec-once = [workspace 4 silent] $telegram
exec-once = [workspace special:overveiw silent] $music
exec-once = /usr/lib/polkit-1
exec-once = killall /usr/libexec/xdg-desktop-portal-hyprland /usr/libexec/xdg-desktop-portal