#Windowrules
windowrulev2 = nomaximizerequest, class:.* 

#Stop Flickering
windowrulev2 = stayfocused, title:^()$,class:^(steam|jetbrains-studio|jetbrains-idea-ce)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam|jetbrains-studio|jetbrains-idea-ce)$

#Opaque Windows
windowrulev2 = opaque,class:^(jetbrains-studio|VSCodium|kitty|jetbrains-idea-ce|librewolf-default)$

#Specific Workspace
windowrulev2 = workspace 3 silent, class:^(discord)$
windowrulev2 = workspace 4 silent, class:^(com.rtosta.zapzap|org.telegram.desktop)$

#Floating windows
windowrulev2 = float, class:^(com.github.neithern.g4music|boxbuddy-rs|org.qbittorrent.qBittorrent|steam)$
windowrulev2 = float, class:^(xdg-desktop-portal-gtk)$

#Size
windowrulev2 = size 30% 70%, class:^(com.github.neithern.g4music)$
windowrulev2 = size 70% 70%, class:^(steam)$
