# MY HYPRLAND CONFIG

# Monitor(s)
monitor=,preferred,auto,auto

# Default Programs
source=~/.config/dotfiles/hyprland/configs/defaultPrograms.conf

# Autostart
source=~/.config/dotfiles/hyprland/configs/startUpApps.conf

#Environment Variables
source=~/.config/dotfiles/hyprland/configs/Envs.conf

#Keybinds
source=~/.config/dotfiles/hyprland/configs/keyBinds.conf

#Window Rules
source=~/.config/dotfiles/hyprland/configs/windowRules.conf

# Variables
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = no
    }
    sensitivity = 0 
}

general {
    gaps_in = 5
    gaps_out = 20
    border_size = 3
    col.active_border = rgb(ebdbb2) 
    col.inactive_border = rgb(665c54)
    layout = dwindle
    allow_tearing = false
}

decoration {
    active_opacity = 1
    inactive_opacity = 0.7
    rounding = 15
    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
    drop_shadow = false
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    preserve_split = yes 
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = off
}

misc {
    force_default_wallpaper = 0
}

device:epic-mouse-v1 {
    sensitivity = -0.5
}

